services:
  # Backend Service
  - type: web
    name: uniconnect-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false # This should be set in Render dashboard
      - key: JWT_SECRET
        sync: false # This should be set in Render dashboard

  # Frontend Service
  - type: static
    name: uniconnect-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    publishPath: frontend/dist
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    envVars:
      - key: VITE_API_BASE_URL
        value: https://uniconnect-backend-b57e.onrender.com/api
      - key: VITE_SOCKET_URL
        value: https://uniconnect-backend-b57e.onrender.com
